#ifndef __EFFECT_IDX_H_
#define __EFFECT_IDX_H_

enum {
    //MIC
    EFFECT_IDX_LOC_MIC_EQ,
    EFFECT_IDX_LOC_MIC_DRC,
    EFFECT_IDX_LOC_MIC_MAGIC,
    EFFECT_IDX_LOC_MIC_ECHO,
    EFFECT_IDX_MIX_DRC,
    EFFECT_IDX_MIX_EQ,
    EFFECT_IDX_MIX_HOWL,

    //MSC
    EFFECT_IDX_MSC_PRE_EQ,
    EFFECT_IDX_MSC_DY_EQ,
    EFFECT_IDX_MSC_MULT_DRC,
    EFFECT_IDX_MSC_ALL_EQ,
    EFFECT_IDX_MSC_ALL_DRC,

    EFFECT_IDX_MSC_NORMAL_EQ,
    EFFECT_IDX_MSC_POP_EQ,
    EFFECT_IDX_MSC_ROCK_EQ,
    EFFECT_IDX_MSC_JAZZ_EQ,
    EFFECT_IDX_MSC_CLASS_EQ,
    EFFECT_IDX_MSC_COUNTRY_EQ,
    EFFECT_IDX_MSC_DAC_DRC,

    //SCO
    EFFECT_IDX_MSC_MSBC_EQ,
    EFFECT_IDX_MSC_MSBC_DRC,
    EFFECT_IDX_MSC_CSVD_EQ,
    EFFECT_IDX_MSC_CVSD_DRC,

    EFFECT_IDX_MAX_NB,
};

#endif // __EFFECT_H_
