#ifndef _HOME_ICON_RES_H
#define _HOME_ICON_RES_H

/* Layout constants generated by tools/gen_home_icons.py */

#define HOME_ICON_RAM_W                 52
#define HOME_ICON_RAM_H                 52
#define HOME_ICON_RAM_SIZE              (8 + HOME_ICON_RAM_W * HOME_ICON_RAM_H * 2)

#define HOME_DASH_RAM_W                 40
#define HOME_DASH_RAM_H                 3
#define HOME_DASH_RAM_SIZE              (8 + HOME_DASH_RAM_W * HOME_DASH_RAM_H * 2)

#define HOME_DIGIT_W                    48
#define HOME_DIGIT_H                    82
#define HOME_DIGIT_MAX_W                48
#define HOME_DIGIT_RAM_MAX_SIZE         7880
#define HOME_DIGIT_GREY_RAM_MAX_SIZE    7880
#define HOME_COLON_W                    24
#define HOME_COLON_H                    82
#define HOME_COLON_RAM_SIZE             3944
#define HOME_COLON_GREY_RAM_SIZE        3944

#define HOME_TEMPF_W                    65
#define HOME_TEMPF_H                    65
#define HOME_TEMPF_RAM_SIZE             8458

#define HOME_STATUS_BT_W                13
#define HOME_STATUS_BT_H                21
#define HOME_STATUS_LOCK_W              17
#define HOME_STATUS_LOCK_H              21
#define HOME_STATUS_BAT_W               51
#define HOME_STATUS_BAT_H               20
#define HOME_STATUS_BT_RAM_SIZE         (8 + HOME_STATUS_BT_W * HOME_STATUS_BT_H * 2)
#define HOME_STATUS_LOCK_RAM_SIZE       (8 + HOME_STATUS_LOCK_W * HOME_STATUS_LOCK_H * 2)
#define HOME_STATUS_BAT_RAM_SIZE        (8 + HOME_STATUS_BAT_W * HOME_STATUS_BAT_H * 2)

#endif
