#ifndef _NEW_HOME_TAB_RES_H
#define _NEW_HOME_TAB_RES_H

/* Generated by tools/gen_new_ui_tab_icons.py */

#define NEW_HOME_TAB_HEAT_W                79
#define NEW_HOME_TAB_HEAT_H                88
#define NEW_HOME_TAB_MODE_W                79
#define NEW_HOME_TAB_MODE_H                88
#define NEW_HOME_TAB_SETUP_W               79
#define NEW_HOME_TAB_SETUP_H               88
#define NEW_HOME_TAB_ICON_MAX_W            79
#define NEW_HOME_TAB_ICON_MAX_H            88
#define NEW_HOME_TAB_RAM_SIZE              13912

#endif

