#ifndef _NEW_TIMEING_RES_H
#define _NEW_TIMEING_RES_H

/* Generated by tools/gen_new_timeing_icons.py */

#define NEW_TIMEING_ICON_RAM_SIZE          9458

#define NEW_TIMEING_NEW_B0_W                 19
#define NEW_TIMEING_NEW_B0_H                 32
#define NEW_TIMEING_NEW_B0_RAM_SIZE          1224

#define NEW_TIMEING_NEW_B1_W                 5
#define NEW_TIMEING_NEW_B1_H                 30
#define NEW_TIMEING_NEW_B1_RAM_SIZE          308

#define NEW_TIMEING_NEW_B2_W                 19
#define NEW_TIMEING_NEW_B2_H                 32
#define NEW_TIMEING_NEW_B2_RAM_SIZE          1224

#define NEW_TIMEING_NEW_B3_W                 19
#define NEW_TIMEING_NEW_B3_H                 32
#define NEW_TIMEING_NEW_B3_RAM_SIZE          1224

#define NEW_TIMEING_NEW_B4_W                 19
#define NEW_TIMEING_NEW_B4_H                 30
#define NEW_TIMEING_NEW_B4_RAM_SIZE          1148

#define NEW_TIMEING_NEW_B5_W                 20
#define NEW_TIMEING_NEW_B5_H                 32
#define NEW_TIMEING_NEW_B5_RAM_SIZE          1288

#define NEW_TIMEING_NEW_B6_W                 19
#define NEW_TIMEING_NEW_B6_H                 32
#define NEW_TIMEING_NEW_B6_RAM_SIZE          1224

#define NEW_TIMEING_NEW_B7_W                 19
#define NEW_TIMEING_NEW_B7_H                 31
#define NEW_TIMEING_NEW_B7_RAM_SIZE          1186

#define NEW_TIMEING_NEW_B8_W                 19
#define NEW_TIMEING_NEW_B8_H                 32
#define NEW_TIMEING_NEW_B8_RAM_SIZE          1224

#define NEW_TIMEING_NEW_B9_W                 20
#define NEW_TIMEING_NEW_B9_H                 32
#define NEW_TIMEING_NEW_B9_RAM_SIZE          1288

#define NEW_TIMEING_NEW_BLUE_BJ1_W                 75
#define NEW_TIMEING_NEW_BLUE_BJ1_H                 63
#define NEW_TIMEING_NEW_BLUE_BJ1_RAM_SIZE          9458

#define NEW_TIMEING_NEW_BLUE_BJ2_W                 101
#define NEW_TIMEING_NEW_BLUE_BJ2_H                 26
#define NEW_TIMEING_NEW_BLUE_BJ2_RAM_SIZE          5260

#define NEW_TIMEING_NEW_DOWN_W                 17
#define NEW_TIMEING_NEW_DOWN_H                 11
#define NEW_TIMEING_NEW_DOWN_RAM_SIZE          382

#define NEW_TIMEING_NEW_GRAY_BJ1_W                 75
#define NEW_TIMEING_NEW_GRAY_BJ1_H                 63
#define NEW_TIMEING_NEW_GRAY_BJ1_RAM_SIZE          9458

#define NEW_TIMEING_NEW_GRAY_BJ2_W                 101
#define NEW_TIMEING_NEW_GRAY_BJ2_H                 26
#define NEW_TIMEING_NEW_GRAY_BJ2_RAM_SIZE          5260

#define NEW_TIMEING_NEW_UP_W                 17
#define NEW_TIMEING_NEW_UP_H                 11
#define NEW_TIMEING_NEW_UP_RAM_SIZE          382

#define NEW_TIMEING_NEW_W0_W                 19
#define NEW_TIMEING_NEW_W0_H                 32
#define NEW_TIMEING_NEW_W0_RAM_SIZE          1224

#define NEW_TIMEING_NEW_W1_W                 5
#define NEW_TIMEING_NEW_W1_H                 30
#define NEW_TIMEING_NEW_W1_RAM_SIZE          308

#define NEW_TIMEING_NEW_W2_W                 19
#define NEW_TIMEING_NEW_W2_H                 32
#define NEW_TIMEING_NEW_W2_RAM_SIZE          1224

#define NEW_TIMEING_NEW_W3_W                 19
#define NEW_TIMEING_NEW_W3_H                 32
#define NEW_TIMEING_NEW_W3_RAM_SIZE          1224

#define NEW_TIMEING_NEW_W4_W                 19
#define NEW_TIMEING_NEW_W4_H                 30
#define NEW_TIMEING_NEW_W4_RAM_SIZE          1148

#define NEW_TIMEING_NEW_W5_W                 20
#define NEW_TIMEING_NEW_W5_H                 32
#define NEW_TIMEING_NEW_W5_RAM_SIZE          1288

#define NEW_TIMEING_NEW_W6_W                 19
#define NEW_TIMEING_NEW_W6_H                 32
#define NEW_TIMEING_NEW_W6_RAM_SIZE          1224

#define NEW_TIMEING_NEW_W7_W                 19
#define NEW_TIMEING_NEW_W7_H                 31
#define NEW_TIMEING_NEW_W7_RAM_SIZE          1186

#define NEW_TIMEING_NEW_W8_W                 19
#define NEW_TIMEING_NEW_W8_H                 32
#define NEW_TIMEING_NEW_W8_RAM_SIZE          1224

#define NEW_TIMEING_NEW_W9_W                 20
#define NEW_TIMEING_NEW_W9_H                 32
#define NEW_TIMEING_NEW_W9_RAM_SIZE          1288

#define NEW_TIMEING_BOX_W                   75
#define NEW_TIMEING_BOX_H                   63

#define NEW_TIMEING_BTN_W                   101
#define NEW_TIMEING_BTN_H                   26

#define NEW_TIMEING_ARROW_W                 17
#define NEW_TIMEING_ARROW_H                 11

#define NEW_TIMEING_DIGIT_W                 19
#define NEW_TIMEING_DIGIT_H                 32
#define NEW_TIMEING_DIGIT_RAM_SIZE          1224

#endif
