#ifndef _NEW_TIME_RES_H
#define _NEW_TIME_RES_H

/* Generated by tools/gen_new_time_icons.py */

#define NEW_TIME_ICON_RAM_SIZE          9458

#define NEW_TIME_NEW_BLUE_BJ1_W                 75
#define NEW_TIME_NEW_BLUE_BJ1_H                 63
#define NEW_TIME_NEW_BLUE_BJ1_RAM_SIZE          9458

#define NEW_TIME_NEW_BLUE_BJ2_W                 101
#define NEW_TIME_NEW_BLUE_BJ2_H                 26
#define NEW_TIME_NEW_BLUE_BJ2_RAM_SIZE          5260

#define NEW_TIME_NEW_BLUE_BJ3_W                 40
#define NEW_TIME_NEW_BLUE_BJ3_H                 24
#define NEW_TIME_NEW_BLUE_BJ3_RAM_SIZE          1928

#define NEW_TIME_NEW_DOWN_W                 17
#define NEW_TIME_NEW_DOWN_H                 11
#define NEW_TIME_NEW_DOWN_RAM_SIZE          382

#define NEW_TIME_NEW_GRAY_BJ1_W                 75
#define NEW_TIME_NEW_GRAY_BJ1_H                 63
#define NEW_TIME_NEW_GRAY_BJ1_RAM_SIZE          9458

#define NEW_TIME_NEW_GRAY_BJ2_W                 101
#define NEW_TIME_NEW_GRAY_BJ2_H                 26
#define NEW_TIME_NEW_GRAY_BJ2_RAM_SIZE          5260

#define NEW_TIME_NEW_GRAY_BJ3_W                 40
#define NEW_TIME_NEW_GRAY_BJ3_H                 24
#define NEW_TIME_NEW_GRAY_BJ3_RAM_SIZE          1928

#define NEW_TIME_NEW_UP_W                 17
#define NEW_TIME_NEW_UP_H                 11
#define NEW_TIME_NEW_UP_RAM_SIZE          382

#ifndef NEW_TIME_BOX_W
#define NEW_TIME_BOX_W                   75
#endif
#ifndef NEW_TIME_BOX_H
#define NEW_TIME_BOX_H                   63
#endif

#ifndef NEW_TIME_BTN_W
#define NEW_TIME_BTN_W                   101
#endif
#ifndef NEW_TIME_BTN_H
#define NEW_TIME_BTN_H                   26
#endif

#ifndef NEW_TIME_AMPM_W
#define NEW_TIME_AMPM_W                  40
#endif
#ifndef NEW_TIME_AMPM_H
#define NEW_TIME_AMPM_H                  24
#endif

#define NEW_TIME_ARROW_W                 17
#define NEW_TIME_ARROW_H                 11

#endif
