#ifndef _NEW_SETUP_RES_H
#define _NEW_SETUP_RES_H

/* Generated by tools/gen_new_setup_icons.py */

#define NEW_SETUP_ICON_RAM_SIZE          21328

#define NEW_SETUP_NEW_CHAGE_W                 260
#define NEW_SETUP_NEW_CHAGE_H                 41
#define NEW_SETUP_NEW_CHAGE_RAM_SIZE          21328

#define NEW_SETUP_NEW_INFO_0_W                 32
#define NEW_SETUP_NEW_INFO_0_H                 32
#define NEW_SETUP_NEW_INFO_0_RAM_SIZE          2056

#define NEW_SETUP_NEW_INFO_1_W                 32
#define NEW_SETUP_NEW_INFO_1_H                 32
#define NEW_SETUP_NEW_INFO_1_RAM_SIZE          2056

#define NEW_SETUP_NEW_LANGUAGE_0_W                 32
#define NEW_SETUP_NEW_LANGUAGE_0_H                 32
#define NEW_SETUP_NEW_LANGUAGE_0_RAM_SIZE          2056

#define NEW_SETUP_NEW_LANGUAGE_1_W                 32
#define NEW_SETUP_NEW_LANGUAGE_1_H                 32
#define NEW_SETUP_NEW_LANGUAGE_1_RAM_SIZE          2056

#define NEW_SETUP_NEW_LEFT_W                 9
#define NEW_SETUP_NEW_LEFT_H                 13
#define NEW_SETUP_NEW_LEFT_RAM_SIZE          242

#define NEW_SETUP_NEW_TIMEING_0_W                 32
#define NEW_SETUP_NEW_TIMEING_0_H                 32
#define NEW_SETUP_NEW_TIMEING_0_RAM_SIZE          2056

#define NEW_SETUP_NEW_TIMEING_1_W                 32
#define NEW_SETUP_NEW_TIMEING_1_H                 32
#define NEW_SETUP_NEW_TIMEING_1_RAM_SIZE          2056

#define NEW_SETUP_SEL_BG_W                 260
#define NEW_SETUP_SEL_BG_H                 41

#define NEW_SETUP_ICON_W                   32
#define NEW_SETUP_ICON_H                   32

#define NEW_SETUP_ARROW_W                  9
#define NEW_SETUP_ARROW_H                  13

#endif
