#ifndef _NEW_HOME_ICON_RES_H
#define _NEW_HOME_ICON_RES_H

/* Generated by tools/gen_new_ui_icons.py */

#define NEW_HOME_LOGO_W                 204
#define NEW_HOME_LOGO_H                 33
#define NEW_HOME_LOGO_RAM_SIZE          (8 + 204 * 33 * 2)

#define NEW_HOME_BT_W                 10
#define NEW_HOME_BT_H                 16
#define NEW_HOME_BT_RAM_SIZE          (8 + 10 * 16 * 2)

#define NEW_HOME_BAT_DL_W                 31
#define NEW_HOME_BAT_DL_H                 17
#define NEW_HOME_BAT_DL_RAM_SIZE          (8 + 31 * 17 * 2)

#define NEW_HOME_BAT_DL1_W                 31
#define NEW_HOME_BAT_DL1_H                 17
#define NEW_HOME_BAT_DL1_RAM_SIZE          (8 + 31 * 17 * 2)

#define NEW_HOME_BAT_DL2_W                 31
#define NEW_HOME_BAT_DL2_H                 17
#define NEW_HOME_BAT_DL2_RAM_SIZE          (8 + 31 * 17 * 2)

#define NEW_HOME_BAT_DL3_W                 31
#define NEW_HOME_BAT_DL3_H                 17
#define NEW_HOME_BAT_DL3_RAM_SIZE          (8 + 31 * 17 * 2)

#define NEW_HOME_BAT_DL4_W                 31
#define NEW_HOME_BAT_DL4_H                 18
#define NEW_HOME_BAT_DL4_RAM_SIZE          (8 + 31 * 18 * 2)

#define NEW_UI_LOCK_W                 80
#define NEW_UI_LOCK_H                 100
#define NEW_UI_LOCK_RAM_SIZE          (8 + 80 * 100 * 2)

#define NEW_UI_UNLOCK_W                 106
#define NEW_UI_UNLOCK_H                 100
#define NEW_UI_UNLOCK_RAM_SIZE          (8 + 106 * 100 * 2)

#define NEW_UI_DIDIAN_W                 320
#define NEW_UI_DIDIAN_H                 240
#define NEW_UI_DIDIAN_RAM_SIZE          (8 + 320 * 240 * 2)

#define NEW_HOME_BAT_W                  31
#define NEW_HOME_BAT_H                  17

#define NEW_HOME_BT_W                   10
#define NEW_HOME_BT_H                   16

#endif
