#ifndef _NEW_MODE_RES_H
#define _NEW_MODE_RES_H

/* Generated by tools/gen_new_mode_icons.py */

#define NEW_MODE_ICON_RAM_SIZE          21328

#define NEW_MODE_NEW_CHAGE_W                 260
#define NEW_MODE_NEW_CHAGE_H                 41
#define NEW_MODE_NEW_CHAGE_RAM_SIZE          21328

#define NEW_MODE_NEW_CHICKEN_0_W                 32
#define NEW_MODE_NEW_CHICKEN_0_H                 32
#define NEW_MODE_NEW_CHICKEN_0_RAM_SIZE          2056

#define NEW_MODE_NEW_CHICKEN_1_W                 32
#define NEW_MODE_NEW_CHICKEN_1_H                 32
#define NEW_MODE_NEW_CHICKEN_1_RAM_SIZE          2056

#define NEW_MODE_NEW_LEFT_W                 9
#define NEW_MODE_NEW_LEFT_H                 13
#define NEW_MODE_NEW_LEFT_RAM_SIZE          242

#define NEW_MODE_NEW_ORDER_0_W                 32
#define NEW_MODE_NEW_ORDER_0_H                 32
#define NEW_MODE_NEW_ORDER_0_RAM_SIZE          2056

#define NEW_MODE_NEW_ORDER_1_W                 32
#define NEW_MODE_NEW_ORDER_1_H                 32
#define NEW_MODE_NEW_ORDER_1_RAM_SIZE          2056

#define NEW_MODE_NEW_PASTA_0_W                 32
#define NEW_MODE_NEW_PASTA_0_H                 32
#define NEW_MODE_NEW_PASTA_0_RAM_SIZE          2056

#define NEW_MODE_NEW_PASTA_1_W                 32
#define NEW_MODE_NEW_PASTA_1_H                 32
#define NEW_MODE_NEW_PASTA_1_RAM_SIZE          2056

#define NEW_MODE_NEW_WARM_0_W                 32
#define NEW_MODE_NEW_WARM_0_H                 32
#define NEW_MODE_NEW_WARM_0_RAM_SIZE          2056

#define NEW_MODE_NEW_WARM_1_W                 32
#define NEW_MODE_NEW_WARM_1_H                 32
#define NEW_MODE_NEW_WARM_1_RAM_SIZE          2056

#define NEW_MODE_SEL_BG_W                 260
#define NEW_MODE_SEL_BG_H                 41

#define NEW_MODE_ICON_W                   32
#define NEW_MODE_ICON_H                   32

#endif
