#!/usr/bin/env python3
"""Generate heat-page GPU bins from Output/bin/ui/new_ui/*.png.

Resources: new_temp_1..5, new_time_1..13, new_point, new_blue_time, new_white_time

Run: python tools/gen_new_heat_icons.py
     Output/bin/prebuild.bat
"""

from __future__ import annotations

import struct
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BIN_DIR = ROOT / "Output" / "bin" / "ui" / "new_ui"
OUT_H = ROOT / "functions" / "new_heat_res.h"

BG_WHITE = (255, 255, 255)

HEAT_ITEMS = (
    *(f"new_temp_{i}.png" for i in range(1, 6)),
    *(f"new_time_{i}.png" for i in range(1, 14)),
    "new_point.png",
    "new_blue_time.png",
    "new_white_time.png",
)


def rgba565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def pack_gpu(w: int, h: int, pixels: list[int]) -> bytes:
    buf = bytearray()
    buf += struct.pack("<IHH", 0x24150, w, h)
    for c in pixels:
        buf += struct.pack("<H", c)
    return bytes(buf)


def pixels_from_rgba(im: Image.Image, bg_rgb: tuple[int, int, int]) -> tuple[int, int, list[int]]:
    w, h = im.size
    px = im.load()
    br, bg, bb = bg_rgb
    out: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 32:
                out.append(rgba565(br, bg, bb))
            else:
                blend = a / 255.0
                inv = 1.0 - blend
                rr = int(r * blend + br * inv + 0.5)
                gg = int(g * blend + bg * inv + 0.5)
                bb2 = int(b * blend + bb * inv + 0.5)
                out.append(rgba565(rr, gg, bb2))
    return w, h, out


def png_to_gpu(path: Path) -> tuple[bytes, int, int]:
    im = Image.open(path).convert("RGBA")
    w, h, pixels = pixels_from_rgba(im, BG_WHITE)
    return pack_gpu(w, h, pixels), w, h


def stem_from_png(name: str) -> str:
    return Path(name).stem


def macro_prefix(stem: str) -> str:
    return "NEW_HEAT_" + stem.upper().replace(".", "_")


def main() -> None:
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    sizes: dict[str, tuple[int, int, int]] = {}
    track_max = 0
    badge_max = 0
    point_sz = 0

    for png_name in HEAT_ITEMS:
        src = BIN_DIR / png_name
        if not src.exists():
            print(f"SKIP: {png_name} not found")
            continue
        data, w, h = png_to_gpu(src)
        stem = stem_from_png(png_name)
        out = BIN_DIR / f"{stem}.bin"
        out.write_bytes(data)
        sizes[stem] = (w, h, len(data))
        print(f"{stem}.bin: {len(data)} bytes ({w}x{h}) <- {png_name}")
        if stem.startswith("new_temp_") or stem.startswith("new_time_"):
            track_max = max(track_max, len(data))
        elif stem in ("new_blue_time", "new_white_time"):
            badge_max = max(badge_max, len(data))
        elif stem == "new_point":
            point_sz = len(data)

    if not sizes:
        print("No heat PNGs found.")
        return

    lines = [
        "#ifndef _NEW_HEAT_RES_H",
        "#define _NEW_HEAT_RES_H",
        "",
        "/* Generated by tools/gen_new_heat_icons.py */",
        "",
        f"#define NEW_HEAT_TRACK_RAM_SIZE           {track_max or 3536}",
        f"#define NEW_HEAT_BADGE_RAM_SIZE           {badge_max or 2978}",
        f"#define NEW_HEAT_POINT_RAM_SIZE           {point_sz or 1466}",
        "",
        "#define NEW_HEAT_TEMP_CNT                 5",
        "#define NEW_HEAT_TIME_CNT                 13",
        "",
    ]

    for stem, (w, h, sz) in sorted(sizes.items()):
        tag = macro_prefix(stem)
        lines.append(f"#define {tag}_W                 {w}")
        lines.append(f"#define {tag}_H                 {h}")
        lines.append(f"#define {tag}_RAM_SIZE          {sz}")
        lines.append("")

    if "new_point" in sizes:
        w, h, _ = sizes["new_point"]
        lines.append(f"#define NEW_HEAT_POINT_W                  {w}")
        lines.append(f"#define NEW_HEAT_POINT_H                  {h}")
        lines.append("")

    if "new_blue_time" in sizes:
        w, h, _ = sizes["new_blue_time"]
        lines.append(f"#define NEW_HEAT_BADGE_W                  {w}")
        lines.append(f"#define NEW_HEAT_BADGE_H                  {h}")
        lines.append("")

    track_w = max(
        (sizes[k][0] for k in sizes if k.startswith("new_temp_") or k.startswith("new_time_")),
        default=252,
    )
    lines.append(f"#define NEW_HEAT_SLIDER_W                 {track_w}")
    lines.append("")
    lines.append("#endif")
    lines.append("")

    OUT_H.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_H}")
    print("Next: run Output/bin/prebuild.bat")


if __name__ == "__main__":
    main()
