#!/usr/bin/env python3
"""Generate setup-page GPU bins from Output/bin/ui/new_ui/*.png.

Icons:
  new_timeing_0/1   Time
  new_language_0/1  Language
  new_info_0/1      Ver. Info.
  new_chage         Selected row background (shared with mode page)
  new_left          Chevron arrow (shared with mode page)

Run: python tools/gen_new_setup_icons.py
     Output/bin/prebuild.bat
"""

from __future__ import annotations

import struct
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BIN_DIR = ROOT / "Output" / "bin" / "ui" / "new_ui"
OUT_H = ROOT / "functions" / "new_setup_res.h"

BG_WHITE = (255, 255, 255)

SETUP_ITEMS = (
    "new_chage.png",
    "new_left.png",
    "new_timeing_0.png",
    "new_timeing_1.png",
    "new_language_0.png",
    "new_language_1.png",
    "new_info_0.png",
    "new_info_1.png",
)


def rgba565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def pack_gpu(w: int, h: int, pixels: list[int]) -> bytes:
    buf = bytearray()
    buf += struct.pack("<IHH", 0x24150, w, h)
    for c in pixels:
        buf += struct.pack("<H", c)
    return bytes(buf)


def pixels_from_rgba(im: Image.Image, bg_rgb: tuple[int, int, int]) -> tuple[int, int, list[int]]:
    w, h = im.size
    px = im.load()
    br, bg, bb = bg_rgb
    out: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 32:
                out.append(rgba565(br, bg, bb))
            else:
                blend = a / 255.0
                inv = 1.0 - blend
                rr = int(r * blend + br * inv + 0.5)
                gg = int(g * blend + bg * inv + 0.5)
                bb2 = int(b * blend + bb * inv + 0.5)
                out.append(rgba565(rr, gg, bb2))
    return w, h, out


def png_to_gpu(path: Path) -> tuple[bytes, int, int]:
    im = Image.open(path).convert("RGBA")
    w, h, pixels = pixels_from_rgba(im, BG_WHITE)
    return pack_gpu(w, h, pixels), w, h


def macro_prefix(stem: str) -> str:
    return "NEW_SETUP_" + stem.upper().replace(".", "_")


def main() -> None:
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    sizes: dict[str, tuple[int, int, int]] = {}
    ram_max = 0

    for png_name in SETUP_ITEMS:
        src = BIN_DIR / png_name
        if not src.exists():
            print(f"SKIP: {png_name} not found")
            continue
        data, w, h = png_to_gpu(src)
        stem = Path(png_name).stem
        out = BIN_DIR / f"{stem}.bin"
        out.write_bytes(data)
        sizes[stem] = (w, h, len(data))
        ram_max = max(ram_max, len(data))
        print(f"{stem}.bin: {len(data)} bytes ({w}x{h})")

    if not sizes:
        print("No setup PNGs found.")
        return

    lines = [
        "#ifndef _NEW_SETUP_RES_H",
        "#define _NEW_SETUP_RES_H",
        "",
        "/* Generated by tools/gen_new_setup_icons.py */",
        "",
        f"#define NEW_SETUP_ICON_RAM_SIZE          {ram_max}",
        "",
    ]

    for stem, (w, h, sz) in sorted(sizes.items()):
        tag = macro_prefix(stem)
        lines.append(f"#define {tag}_W                 {w}")
        lines.append(f"#define {tag}_H                 {h}")
        lines.append(f"#define {tag}_RAM_SIZE          {sz}")
        lines.append("")

    if "new_chage" in sizes:
        w, h, _ = sizes["new_chage"]
        lines.append(f"#define NEW_SETUP_SEL_BG_W                 {w}")
        lines.append(f"#define NEW_SETUP_SEL_BG_H                 {h}")
        lines.append("")

    if "new_timeing_0" in sizes:
        w, h, _ = sizes["new_timeing_0"]
        lines.append(f"#define NEW_SETUP_ICON_W                   {w}")
        lines.append(f"#define NEW_SETUP_ICON_H                   {h}")
        lines.append("")

    if "new_left" in sizes:
        w, h, _ = sizes["new_left"]
        lines.append(f"#define NEW_SETUP_ARROW_W                  {w}")
        lines.append(f"#define NEW_SETUP_ARROW_H                  {h}")
        lines.append("")

    lines.append("#endif")
    lines.append("")

    OUT_H.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_H}")
    print("Next: run Output/bin/prebuild.bat")


if __name__ == "__main__":
    main()
