#!/usr/bin/env python3
"""Generate time-setting page GPU bins from Output/bin/ui/new_ui/*.png.

  new_blue_bj1 / new_gray_bj1   Hour/Min digit boxes
  new_blue_bj2 / new_gray_bj2   NO / YES buttons
  new_up / new_down             Arrow chevrons
  new_b0..9 / new_w0..9         Black/white segment digits

Run: python tools/gen_new_timeing_icons.py
     python tools/gen_new_time_icons.py   (if bj/up/down PNGs changed)
     Output/bin/prebuild.bat
"""

from __future__ import annotations

import struct
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BIN_DIR = ROOT / "Output" / "bin" / "ui" / "new_ui"
OUT_H = ROOT / "functions" / "new_timeing_res.h"

BG_WHITE = (255, 255, 255)

TIME_ITEMS = (
    "new_blue_bj1.png",
    "new_gray_bj1.png",
    "new_blue_bj2.png",
    "new_gray_bj2.png",
    "new_up.png",
    "new_down.png",
)

DIGIT_ITEMS = tuple(f"new_{prefix}{d}.png" for prefix in ("b", "w") for d in range(10))


def rgba565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def pack_gpu(w: int, h: int, pixels: list[int]) -> bytes:
    buf = bytearray()
    buf += struct.pack("<IHH", 0x24150, w, h)
    for c in pixels:
        buf += struct.pack("<H", c)
    return bytes(buf)


def pixels_from_rgba(im: Image.Image, bg_rgb: tuple[int, int, int]) -> tuple[int, int, list[int]]:
    w, h = im.size
    px = im.load()
    br, bg, bb = bg_rgb
    out: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 32:
                out.append(rgba565(br, bg, bb))
            else:
                blend = a / 255.0
                inv = 1.0 - blend
                rr = int(r * blend + br * inv + 0.5)
                gg = int(g * blend + bg * inv + 0.5)
                bb2 = int(b * blend + bb * inv + 0.5)
                out.append(rgba565(rr, gg, bb2))
    return w, h, out


def png_to_gpu(path: Path) -> tuple[bytes, int, int]:
    im = Image.open(path).convert("RGBA")
    w, h, pixels = pixels_from_rgba(im, BG_WHITE)
    return pack_gpu(w, h, pixels), w, h


def macro_prefix(stem: str) -> str:
    return "NEW_TIMEING_" + stem.upper().replace(".", "_")


def read_bin_size(bin_path: Path) -> tuple[int, int, int]:
    data = bin_path.read_bytes()
    if len(data) < 8:
        raise ValueError(f"bad gpu bin: {bin_path}")
    w, h = struct.unpack("<HH", data[4:8])
    return w, h, len(data)


def process_item(png_name: str, sizes: dict[str, tuple[int, int, int]]) -> int:
    stem = Path(png_name).stem
    src = BIN_DIR / png_name
    out = BIN_DIR / f"{stem}.bin"
    ram_max = 0

    if src.exists():
        data, w, h = png_to_gpu(src)
        out.write_bytes(data)
        sizes[stem] = (w, h, len(data))
        ram_max = len(data)
        print(f"{stem}.bin: {len(data)} bytes ({w}x{h}) <- {png_name}")
        return ram_max

    if out.exists():
        w, h, sz = read_bin_size(out)
        sizes[stem] = (w, h, sz)
        ram_max = sz
        print(f"{stem}.bin: keep existing {sz} bytes ({w}x{h})")
        return ram_max

    print(f"SKIP: {png_name} not found")
    return 0


def main() -> None:
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    sizes: dict[str, tuple[int, int, int]] = {}
    ram_max = 0

    for png_name in TIME_ITEMS + DIGIT_ITEMS:
        ram_max = max(ram_max, process_item(png_name, sizes))

    if not sizes:
        print("No timeing PNGs found.")
        return

    lines = [
        "#ifndef _NEW_TIMEING_RES_H",
        "#define _NEW_TIMEING_RES_H",
        "",
        "/* Generated by tools/gen_new_timeing_icons.py */",
        "",
        f"#define NEW_TIMEING_ICON_RAM_SIZE          {ram_max}",
        "",
    ]

    for stem, (w, h, sz) in sorted(sizes.items()):
        tag = macro_prefix(stem)
        lines.append(f"#define {tag}_W                 {w}")
        lines.append(f"#define {tag}_H                 {h}")
        lines.append(f"#define {tag}_RAM_SIZE          {sz}")
        lines.append("")

    if "new_blue_bj1" in sizes:
        w, h, _ = sizes["new_blue_bj1"]
        lines.append(f"#define NEW_TIMEING_BOX_W                   {w}")
        lines.append(f"#define NEW_TIMEING_BOX_H                   {h}")
        lines.append("")

    if "new_blue_bj2" in sizes:
        w, h, _ = sizes["new_blue_bj2"]
        lines.append(f"#define NEW_TIMEING_BTN_W                   {w}")
        lines.append(f"#define NEW_TIMEING_BTN_H                   {h}")
        lines.append("")

    if "new_up" in sizes:
        w, h, _ = sizes["new_up"]
        lines.append(f"#define NEW_TIMEING_ARROW_W                 {w}")
        lines.append(f"#define NEW_TIMEING_ARROW_H                 {h}")
        lines.append("")

    if "new_b0" in sizes:
        w, h, sz = sizes["new_b0"]
        lines.append(f"#define NEW_TIMEING_DIGIT_W                 {w}")
        lines.append(f"#define NEW_TIMEING_DIGIT_H                 {h}")
        lines.append(f"#define NEW_TIMEING_DIGIT_RAM_SIZE          {sz}")
        lines.append("")

    lines.append("#endif")
    lines.append("")

    OUT_H.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_H}")
    print("Next: run Output/bin/prebuild.bat")


if __name__ == "__main__":
    main()
