#!/usr/bin/env python3
"""Generate nav tab .bin + header from Output/bin/ui/new_ui/*.png.

Full-size icons (79x88); RAM in home_ui_shared_icon_runtime[] (static BSS).

Run: python tools/gen_new_ui_tab_icons.py
     Output/bin/prebuild.bat
"""

from __future__ import annotations

import struct
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
BIN_DIR = ROOT / "Output" / "bin" / "ui" / "new_ui"

BG_WHITE = (255, 255, 255)

TAB_NAMES = (
    ("HEAT_0.png", "HEAT_0"),
    ("HEAT_1.png", "HEAT_1"),
    ("MODE_0.png", "MODE_0"),
    ("MODE_1.png", "MODE_1"),
    ("SETUP_0.png", "SETUP_0"),
    ("SETUP_1.png", "SETUP_1"),
)

OUT_H = ROOT / "functions" / "new_home_tab_res.h"


def rgba565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def pack_gpu(w: int, h: int, pixels: list[int]) -> bytes:
    buf = bytearray()
    buf += struct.pack("<IHH", 0x24150, w, h)
    for c in pixels:
        buf += struct.pack("<H", c)
    return bytes(buf)


def png_to_gpu(path: Path) -> tuple[bytes, int, int]:
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    px = im.load()
    bg = rgba565(*BG_WHITE)
    out: list[int] = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 32:
                out.append(bg)
            else:
                out.append(rgba565(r, g, b))
    return pack_gpu(w, h, out), w, h


def main() -> None:
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    sizes: dict[str, tuple[int, int]] = {}
    ram_max = 0

    for png_name, stem in TAB_NAMES:
        src = BIN_DIR / png_name
        if not src.exists():
            print(f"SKIP: {png_name} not found")
            continue
        data, w, h = png_to_gpu(src)
        out_name = f"{stem}.bin"
        out = BIN_DIR / out_name
        out.write_bytes(data)
        sizes[stem] = (w, h)
        sz = len(data)
        ram_max = max(ram_max, sz)
        print(f"{out_name}: {sz} bytes ({w}x{h}) <- {png_name}")

    if not sizes:
        print("No tab PNGs found. Nothing done.")
        return

    heat_w = sizes.get("HEAT_1", sizes.get("HEAT_0", (79, 88)))[0]
    heat_h = sizes.get("HEAT_1", sizes.get("HEAT_0", (79, 88)))[1]
    mode_w = sizes.get("MODE_1", sizes.get("MODE_0", (79, 88)))[0]
    mode_h = sizes.get("MODE_1", sizes.get("MODE_0", (79, 88)))[1]
    setup_w = sizes.get("SETUP_1", sizes.get("SETUP_0", (79, 88)))[0]
    setup_h = sizes.get("SETUP_1", sizes.get("SETUP_0", (79, 88)))[1]
    icon_max_w = max(heat_w, mode_w, setup_w)
    icon_max_h = max(heat_h, mode_h, setup_h)
    ram_max = 8 + icon_max_w * icon_max_h * 2

    lines = [
        "#ifndef _NEW_HOME_TAB_RES_H",
        "#define _NEW_HOME_TAB_RES_H",
        "",
        "/* Generated by tools/gen_new_ui_tab_icons.py */",
        "",
        f"#define NEW_HOME_TAB_HEAT_W                {heat_w}",
        f"#define NEW_HOME_TAB_HEAT_H                {heat_h}",
        f"#define NEW_HOME_TAB_MODE_W                {mode_w}",
        f"#define NEW_HOME_TAB_MODE_H                {mode_h}",
        f"#define NEW_HOME_TAB_SETUP_W               {setup_w}",
        f"#define NEW_HOME_TAB_SETUP_H               {setup_h}",
        f"#define NEW_HOME_TAB_ICON_MAX_W            {icon_max_w}",
        f"#define NEW_HOME_TAB_ICON_MAX_H            {icon_max_h}",
        f"#define NEW_HOME_TAB_RAM_SIZE              {ram_max}",
        "",
        "#endif",
        "",
    ]
    OUT_H.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_H}")
    print(f"ram_max={ram_max}")


if __name__ == "__main__":
    main()
